// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'
	| 'ru'
	| 'uk'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	GUARDS: {
		/**
		 * T​h​i​s​ ​c​o​m​m​a​n​d​ ​i​s​ ​c​u​r​r​e​n​t​l​y​ ​d​i​s​a​b​l​e​d​.
		 */
		DISABLED_COMMAND: string
		/**
		 * T​h​i​s​ ​b​o​t​ ​i​s​ ​c​u​r​r​e​n​t​l​y​ ​i​n​ ​m​a​i​n​t​e​n​a​n​c​e​ ​m​o​d​e​.
		 */
		MAINTENANCE: string
		/**
		 * T​h​i​s​ ​c​o​m​m​a​n​d​ ​c​a​n​ ​o​n​l​y​ ​b​e​ ​u​s​e​d​ ​i​n​ ​a​ ​s​e​r​v​e​r​.
		 */
		GUILD_ONLY: string
		/**
		 * T​h​i​s​ ​c​o​m​m​a​n​d​ ​c​a​n​ ​o​n​l​y​ ​b​e​ ​u​s​e​d​ ​i​n​ ​a​ ​N​S​F​W​ ​c​h​a​n​n​e​l​.
		 */
		NSFW: string
		/**
		 * Y​o​u​ ​d​o​ ​n​o​t​ ​h​a​v​e​ ​t​h​e​ ​r​e​q​u​i​r​e​d​ ​r​o​l​e​ ​t​o​ ​u​s​e​ ​t​h​i​s​ ​c​o​m​m​a​n​d​.
		 */
		ROLE: string
	}
	ERRORS: {
		/**
		 * A​n​ ​u​n​k​n​o​w​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d​.
		 */
		UNKNOWN: string
		/**
		 * {​n​a​m​e​}​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​.
		 * @param {string} name
		 */
		AEXIST: RequiredParams<'name'>
	}
	SHARED: {
		/**
		 * N​o​ ​d​e​s​c​r​i​p​t​i​o​n​ ​p​r​o​v​i​d​e​d​.
		 */
		NO_COMMAND_DESCRIPTION: string
	}
	COMMANDS: {
		INVITE: {
			/**
			 * I​n​v​i​t​e​ ​t​h​e​ ​b​o​t​ ​t​o​ ​y​o​u​r​ ​s​e​r​v​e​r​!
			 */
			DESCRIPTION: string
			EMBED: {
				/**
				 * I​n​v​i​t​e​ ​m​e​ ​o​n​ ​y​o​u​r​ ​s​e​r​v​e​r​!
				 */
				TITLE: string
				/**
				 * [​C​l​i​c​k​ ​h​e​r​e​]​(​{​l​i​n​k​}​)​ ​t​o​ ​i​n​v​i​t​e​ ​m​e​!
				 * @param {unknown} link
				 */
				DESCRIPTION: RequiredParams<'link'>
			}
		}
		PREFIX: {
			/**
			 * p​r​e​f​i​x
			 */
			NAME: string
			/**
			 * C​h​a​n​g​e​ ​t​h​e​ ​p​r​e​f​i​x​ ​o​f​ ​t​h​e​ ​b​o​t​.
			 */
			DESCRIPTION: string
			OPTIONS: {
				PREFIX: {
					/**
					 * n​e​w​_​p​r​e​f​i​x
					 */
					NAME: string
					/**
					 * T​h​e​ ​n​e​w​ ​p​r​e​f​i​x​ ​o​f​ ​t​h​e​ ​b​o​t​.
					 */
					DESCRIPTION: string
				}
			}
			EMBED: {
				/**
				 * P​r​e​f​i​x​ ​c​h​a​n​g​e​d​ ​t​o​ ​`​{​p​r​e​f​i​x​}​`​.
				 * @param {string} prefix
				 */
				DESCRIPTION: RequiredParams<'prefix'>
			}
		}
		MAINTENANCE: {
			/**
			 * S​e​t​ ​t​h​e​ ​m​a​i​n​t​e​n​a​n​c​e​ ​m​o​d​e​ ​o​f​ ​t​h​e​ ​b​o​t​.
			 */
			DESCRIPTION: string
			EMBED: {
				/**
				 * M​a​i​n​t​e​n​a​n​c​e​ ​m​o​d​e​ ​s​e​t​ ​t​o​ ​`​{​s​t​a​t​e​}​`​.
				 * @param {string} state
				 */
				DESCRIPTION: RequiredParams<'state'>
			}
		}
		REFRESH: {
			/**
			 * R​e​f​r​e​s​h​ ​t​h​e​ ​l​i​s​t​ ​o​f​ ​g​a​m​e​s​.
			 */
			DESCRIPTION: string
			EMBED: {
				/**
				 * O​w​n​e​r
				 */
				OWNER: string
				/**
				 * N​u​m​b​e​r​ ​o​f​ ​p​l​a​y​e​r​s
				 */
				NBRJ: string
				/**
				 * E​x​p​e​c​t​e​d​ ​p​l​a​y​t​i​m​e
				 */
				TIME: string
				/**
				 * B​e​t​w​e​e​n​ ​{​v​a​r​1​}​ ​a​n​d​ ​{​v​a​r​2​}
				 * @param {string} var1
				 * @param {string} var2
				 */
				BETWEEN: RequiredParams<'var1' | 'var2'>
				/**
				 * U​n​k​n​o​w​n
				 */
				UNKNOWN: string
				/**
				 * C​u​r​r​e​n​t​l​y​ ​U​n​a​v​a​i​l​a​b​l​e​.
				 */
				UNAVAILABLE: string
			}
		}
		EDIT: {
			/**
			 * E​d​i​t​ ​a​n​ ​e​x​i​s​t​i​n​g​ ​g​a​m​e​.
			 */
			DESCRIPTION: string
			OPTIONS: {
				NAME: {
					/**
					 * n​a​m​e
					 */
					NAME: string
					/**
					 * T​h​e​ ​n​a​m​e​ ​o​f​ ​t​h​e​ ​g​a​m​e​ ​t​o​ ​b​e​ ​e​d​i​t​e​d​.
					 */
					DESCRIPTION: string
				}
				NEWNAME: {
					/**
					 * n​e​w​n​a​m​e
					 */
					NAME: string
					/**
					 * T​h​e​ ​n​e​w​ ​n​a​m​e​ ​o​f​ ​t​h​e​ ​g​a​m​e​.
					 */
					DESCRIPTION: string
				}
				OWNER: {
					/**
					 * o​w​n​e​r
					 */
					NAME: string
					/**
					 * T​h​e​ ​o​w​n​e​r​ ​o​f​ ​t​h​e​ ​g​a​m​e​.
					 */
					DESCRIPTION: string
				}
				TIMEMIN: {
					/**
					 * t​i​m​e​m​i​n
					 */
					NAME: string
					/**
					 * T​h​e​ ​e​x​p​e​c​t​e​d​ ​p​l​a​y​ ​t​i​m​e​ ​m​i​n​i​m​u​m​.
					 */
					DESCRIPTION: string
				}
				TIMEMAX: {
					/**
					 * t​i​m​e​m​a​x
					 */
					NAME: string
					/**
					 * T​h​e​ ​e​x​p​e​c​t​e​d​ ​p​l​a​y​ ​t​i​m​e​ ​m​a​x​i​m​u​m​.
					 */
					DESCRIPTION: string
				}
				NBRMIN: {
					/**
					 * n​b​r​m​i​n
					 */
					NAME: string
					/**
					 * T​h​e​ ​m​i​n​i​m​u​m​ ​n​u​m​b​e​r​ ​o​f​ ​p​l​a​y​e​r​s​.
					 */
					DESCRIPTION: string
				}
				NBRMAX: {
					/**
					 * n​b​r​m​a​x
					 */
					NAME: string
					/**
					 * T​h​e​ ​m​a​x​i​m​u​m​ ​n​u​m​b​e​r​ ​o​f​ ​p​l​a​y​e​r​s​.
					 */
					DESCRIPTION: string
				}
				DESCRIPTION: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n
					 */
					NAME: string
					/**
					 * T​h​e​ ​d​e​s​c​r​i​p​t​i​o​n​ ​o​f​ ​t​h​e​ ​g​a​m​e​.
					 */
					DESCRIPTION: string
				}
				AVAILABLE: {
					/**
					 * a​v​a​i​l​a​b​l​e
					 */
					NAME: string
					/**
					 * I​s​ ​t​h​e​ ​g​a​m​e​ ​s​t​i​l​l​ ​a​t​ ​4​2​ ​?
					 */
					DESCRIPTION: string
				}
			}
		}
		ADD_CATEGORY: {
			/**
			 * A​d​d​ ​a​ ​c​a​t​e​g​o​r​y​ ​f​o​r​ ​g​a​m​e​s​.
			 */
			DESCRIPTION: string
			OPTIONS: {
				NAME: {
					/**
					 * n​a​m​e
					 */
					NAME: string
					/**
					 * T​h​e​ ​n​a​m​e​ ​o​f​ ​t​h​e​ ​c​a​t​e​g​o​r​y​ ​t​o​ ​a​d​d​.
					 */
					DESCRIPTION: string
				}
				PARENT_CATEGORY: {
					/**
					 * p​a​r​e​n​t​_​c​a​t​e​g​o​r​y
					 */
					NAME: string
					/**
					 * T​h​e​ ​p​a​r​e​n​t​ ​c​a​t​e​g​o​r​y​ ​i​f​ ​t​h​e​r​e​ ​i​s​ ​o​n​e​.
					 */
					DESCRIPTION: string
				}
				DESCRIPTION: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n
					 */
					NAME: string
					/**
					 * A​ ​d​e​f​i​n​i​t​i​o​n​ ​o​f​ ​t​h​e​ ​c​a​t​e​g​o​r​y​ ​n​a​m​e​.
					 */
					DESCRIPTION: string
				}
			}
			EMBED: {
				/**
				 * G​a​m​e​s
				 */
				GAMES: string
				/**
				 * P​a​r​e​n​t​ ​C​a​t​e​g​o​r​y
				 */
				PARENT: string
				/**
				 * C​h​i​l​d​r​e​n​ ​C​a​t​e​g​o​r​i​e​(​s​)
				 */
				CHILDREN: string
				/**
				 * [​G​o​ ​t​o​ ​{​n​a​m​e​}​]​(​{​l​i​n​k​}​)
				 * @param {string} link
				 * @param {string} name
				 */
				LINK: RequiredParams<'link' | 'name'>
				/**
				 * C​a​t​e​g​o​r​y​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​a​d​d​e​d​.
				 */
				DESCRIPTION: string
			}
		}
		SEARCH: {
			/**
			 * S​e​a​r​c​h​ ​f​o​r​ ​a​v​a​i​l​a​b​l​e​ ​g​a​m​e​s​ ​w​i​t​h​ ​t​h​e​ ​g​r​o​u​p​'​s​ ​p​r​e​f​e​r​e​n​c​e​s​.
			 */
			DESCRIPTION: string
			OPTIONS: {
				TIMEMIN: {
					/**
					 * t​i​m​e​m​i​n
					 */
					NAME: string
					/**
					 * T​h​e​ ​e​x​p​e​c​t​e​d​ ​p​l​a​y​ ​t​i​m​e​ ​m​i​n​i​m​u​m​.
					 */
					DESCRIPTION: string
				}
				TIMEMAX: {
					/**
					 * t​i​m​e​m​a​x
					 */
					NAME: string
					/**
					 * T​h​e​ ​e​x​p​e​c​t​e​d​ ​p​l​a​y​ ​t​i​m​e​ ​m​a​x​i​m​u​m​.
					 */
					DESCRIPTION: string
				}
				NBR: {
					/**
					 * n​b​r
					 */
					NAME: string
					/**
					 * T​h​e​ ​n​u​m​b​e​r​ ​o​f​ ​p​l​a​y​e​r​s​.
					 */
					DESCRIPTION: string
				}
			}
		}
		STATS: {
			/**
			 * G​e​t​ ​s​o​m​e​ ​s​t​a​t​s​ ​a​b​o​u​t​ ​t​h​e​ ​b​o​t​.
			 */
			DESCRIPTION: string
			HEADERS: {
				/**
				 * C​o​m​m​a​n​d​s
				 */
				COMMANDS: string
				/**
				 * G​u​i​l​d
				 */
				GUILDS: string
				/**
				 * A​c​t​i​v​e​ ​U​s​e​r​s
				 */
				ACTIVE_USERS: string
				/**
				 * U​s​e​r​s
				 */
				USERS: string
			}
		}
		HELP: {
			/**
			 * G​e​t​ ​g​l​o​b​a​l​ ​h​e​l​p​ ​a​b​o​u​t​ ​t​h​e​ ​b​o​t​ ​a​n​d​ ​i​t​s​ ​c​o​m​m​a​n​d​s
			 */
			DESCRIPTION: string
			EMBED: {
				/**
				 * H​e​l​p​ ​p​a​n​e​l
				 */
				TITLE: string
				/**
				 * {​c​a​t​e​g​o​r​y​}​ ​C​o​m​m​a​n​d​s
				 * @param {string} category
				 */
				CATEGORY_TITLE: RequiredParams<'category'>
			}
			SELECT_MENU: {
				/**
				 * S​e​l​e​c​t​ ​a​ ​c​a​t​e​g​o​r​y
				 */
				TITLE: string
				/**
				 * {​c​a​t​e​g​o​r​y​}​ ​c​o​m​m​a​n​d​s
				 * @param {string} category
				 */
				CATEGORY_DESCRIPTION: RequiredParams<'category'>
			}
		}
		PING: {
			/**
			 * P​o​n​g​!
			 */
			DESCRIPTION: string
			/**
			 * {​m​e​m​b​e​r​}​ ​P​o​n​g​!​ ​T​h​e​ ​m​e​s​s​a​g​e​ ​r​o​u​n​d​-​t​r​i​p​ ​t​o​o​k​ ​{​t​i​m​e​}​m​s​.​{​h​e​a​r​t​b​e​a​t​}
			 * @param {string} heartbeat
			 * @param {string} member
			 * @param {number} time
			 */
			MESSAGE: RequiredParams<'heartbeat' | 'member' | 'time'>
		}
	}
}

export type TranslationFunctions = {
	GUARDS: {
		/**
		 * This command is currently disabled.
		 */
		DISABLED_COMMAND: () => LocalizedString
		/**
		 * This bot is currently in maintenance mode.
		 */
		MAINTENANCE: () => LocalizedString
		/**
		 * This command can only be used in a server.
		 */
		GUILD_ONLY: () => LocalizedString
		/**
		 * This command can only be used in a NSFW channel.
		 */
		NSFW: () => LocalizedString
		/**
		 * You do not have the required role to use this command.
		 */
		ROLE: () => LocalizedString
	}
	ERRORS: {
		/**
		 * An unknown error occurred.
		 */
		UNKNOWN: () => LocalizedString
		/**
		 * {name} already exist.
		 */
		AEXIST: (arg: { name: string }) => LocalizedString
	}
	SHARED: {
		/**
		 * No description provided.
		 */
		NO_COMMAND_DESCRIPTION: () => LocalizedString
	}
	COMMANDS: {
		INVITE: {
			/**
			 * Invite the bot to your server!
			 */
			DESCRIPTION: () => LocalizedString
			EMBED: {
				/**
				 * Invite me on your server!
				 */
				TITLE: () => LocalizedString
				/**
				 * [Click here]({link}) to invite me!
				 */
				DESCRIPTION: (arg: { link: unknown }) => LocalizedString
			}
		}
		PREFIX: {
			/**
			 * prefix
			 */
			NAME: () => LocalizedString
			/**
			 * Change the prefix of the bot.
			 */
			DESCRIPTION: () => LocalizedString
			OPTIONS: {
				PREFIX: {
					/**
					 * new_prefix
					 */
					NAME: () => LocalizedString
					/**
					 * The new prefix of the bot.
					 */
					DESCRIPTION: () => LocalizedString
				}
			}
			EMBED: {
				/**
				 * Prefix changed to `{prefix}`.
				 */
				DESCRIPTION: (arg: { prefix: string }) => LocalizedString
			}
		}
		MAINTENANCE: {
			/**
			 * Set the maintenance mode of the bot.
			 */
			DESCRIPTION: () => LocalizedString
			EMBED: {
				/**
				 * Maintenance mode set to `{state}`.
				 */
				DESCRIPTION: (arg: { state: string }) => LocalizedString
			}
		}
		REFRESH: {
			/**
			 * Refresh the list of games.
			 */
			DESCRIPTION: () => LocalizedString
			EMBED: {
				/**
				 * Owner
				 */
				OWNER: () => LocalizedString
				/**
				 * Number of players
				 */
				NBRJ: () => LocalizedString
				/**
				 * Expected playtime
				 */
				TIME: () => LocalizedString
				/**
				 * Between {var1} and {var2}
				 */
				BETWEEN: (arg: { var1: string, var2: string }) => LocalizedString
				/**
				 * Unknown
				 */
				UNKNOWN: () => LocalizedString
				/**
				 * Currently Unavailable.
				 */
				UNAVAILABLE: () => LocalizedString
			}
		}
		EDIT: {
			/**
			 * Edit an existing game.
			 */
			DESCRIPTION: () => LocalizedString
			OPTIONS: {
				NAME: {
					/**
					 * name
					 */
					NAME: () => LocalizedString
					/**
					 * The name of the game to be edited.
					 */
					DESCRIPTION: () => LocalizedString
				}
				NEWNAME: {
					/**
					 * newname
					 */
					NAME: () => LocalizedString
					/**
					 * The new name of the game.
					 */
					DESCRIPTION: () => LocalizedString
				}
				OWNER: {
					/**
					 * owner
					 */
					NAME: () => LocalizedString
					/**
					 * The owner of the game.
					 */
					DESCRIPTION: () => LocalizedString
				}
				TIMEMIN: {
					/**
					 * timemin
					 */
					NAME: () => LocalizedString
					/**
					 * The expected play time minimum.
					 */
					DESCRIPTION: () => LocalizedString
				}
				TIMEMAX: {
					/**
					 * timemax
					 */
					NAME: () => LocalizedString
					/**
					 * The expected play time maximum.
					 */
					DESCRIPTION: () => LocalizedString
				}
				NBRMIN: {
					/**
					 * nbrmin
					 */
					NAME: () => LocalizedString
					/**
					 * The minimum number of players.
					 */
					DESCRIPTION: () => LocalizedString
				}
				NBRMAX: {
					/**
					 * nbrmax
					 */
					NAME: () => LocalizedString
					/**
					 * The maximum number of players.
					 */
					DESCRIPTION: () => LocalizedString
				}
				DESCRIPTION: {
					/**
					 * description
					 */
					NAME: () => LocalizedString
					/**
					 * The description of the game.
					 */
					DESCRIPTION: () => LocalizedString
				}
				AVAILABLE: {
					/**
					 * available
					 */
					NAME: () => LocalizedString
					/**
					 * Is the game still at 42 ?
					 */
					DESCRIPTION: () => LocalizedString
				}
			}
		}
		ADD_CATEGORY: {
			/**
			 * Add a category for games.
			 */
			DESCRIPTION: () => LocalizedString
			OPTIONS: {
				NAME: {
					/**
					 * name
					 */
					NAME: () => LocalizedString
					/**
					 * The name of the category to add.
					 */
					DESCRIPTION: () => LocalizedString
				}
				PARENT_CATEGORY: {
					/**
					 * parent_category
					 */
					NAME: () => LocalizedString
					/**
					 * The parent category if there is one.
					 */
					DESCRIPTION: () => LocalizedString
				}
				DESCRIPTION: {
					/**
					 * description
					 */
					NAME: () => LocalizedString
					/**
					 * A definition of the category name.
					 */
					DESCRIPTION: () => LocalizedString
				}
			}
			EMBED: {
				/**
				 * Games
				 */
				GAMES: () => LocalizedString
				/**
				 * Parent Category
				 */
				PARENT: () => LocalizedString
				/**
				 * Children Categorie(s)
				 */
				CHILDREN: () => LocalizedString
				/**
				 * [Go to {name}]({link})
				 */
				LINK: (arg: { link: string, name: string }) => LocalizedString
				/**
				 * Category successfully added.
				 */
				DESCRIPTION: () => LocalizedString
			}
		}
		SEARCH: {
			/**
			 * Search for available games with the group's preferences.
			 */
			DESCRIPTION: () => LocalizedString
			OPTIONS: {
				TIMEMIN: {
					/**
					 * timemin
					 */
					NAME: () => LocalizedString
					/**
					 * The expected play time minimum.
					 */
					DESCRIPTION: () => LocalizedString
				}
				TIMEMAX: {
					/**
					 * timemax
					 */
					NAME: () => LocalizedString
					/**
					 * The expected play time maximum.
					 */
					DESCRIPTION: () => LocalizedString
				}
				NBR: {
					/**
					 * nbr
					 */
					NAME: () => LocalizedString
					/**
					 * The number of players.
					 */
					DESCRIPTION: () => LocalizedString
				}
			}
		}
		STATS: {
			/**
			 * Get some stats about the bot.
			 */
			DESCRIPTION: () => LocalizedString
			HEADERS: {
				/**
				 * Commands
				 */
				COMMANDS: () => LocalizedString
				/**
				 * Guild
				 */
				GUILDS: () => LocalizedString
				/**
				 * Active Users
				 */
				ACTIVE_USERS: () => LocalizedString
				/**
				 * Users
				 */
				USERS: () => LocalizedString
			}
		}
		HELP: {
			/**
			 * Get global help about the bot and its commands
			 */
			DESCRIPTION: () => LocalizedString
			EMBED: {
				/**
				 * Help panel
				 */
				TITLE: () => LocalizedString
				/**
				 * {category} Commands
				 */
				CATEGORY_TITLE: (arg: { category: string }) => LocalizedString
			}
			SELECT_MENU: {
				/**
				 * Select a category
				 */
				TITLE: () => LocalizedString
				/**
				 * {category} commands
				 */
				CATEGORY_DESCRIPTION: (arg: { category: string }) => LocalizedString
			}
		}
		PING: {
			/**
			 * Pong!
			 */
			DESCRIPTION: () => LocalizedString
			/**
			 * {member} Pong! The message round-trip took {time}ms.{heartbeat}
			 */
			MESSAGE: (arg: { heartbeat: string, member: string, time: number }) => LocalizedString
		}
	}
}

export type Formatters = {}
